# ===============================
# POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante
spring.datasource.username=postgres
spring.datasource.password=Postgres2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ESTA LÍNEA SE PUEDE ELIMINAR
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# JWT
# ===============================

jwt.secret=claveSecretaDelRestaurante2026QueDeberiaSerMasLargaYSegura
jwt.expiration=86400000

# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized